### ISSUE TITLE
Pen Test Result - Terms of Use

### ISSUE THREAD

**Issue by JarredOlson** [SmartColumbusOS/smartcitiesdata#2]
Due: 07/01/2020

The application does not have a page defining the terms of use or legal notice. The application must provide information that unauthorized use of the application will be penalized.	"Add a view describing the terms of use or legal notice in the application. This can be provided as a link from the home screen, or via the help function in the application. Work with the client for the preferred language.

For the legal notice, please refer to Legal Notice section of the Logging and Auditing standard. https://ts.accenture.com/:w:/r/sites/Information_Security2/Protecting%20Accenture/_layouts/15/Doc.aspx?sourcedoc=%7b669A024A-0026-4F05-8458-DD76321A3CA5%7d&file=LoggingandAuditngStandard.docx&action=default&mobileredirect=true&cid=0eb1c832-c416-4b7e-a087-f673917635f5"

**Comment by warnerAWESOMEmoore** [comment]
Sherry's working on standardizing our privacy policy and terms of service across most published Smart Columbus assets. Is there something that we should incorporate?

**Comment by JarredOlson** [comment]
@warnerAWESOMEmoore would that include a Terms of Use?

**Comment by warnerAWESOMEmoore** [comment]
Yes, that's my understanding.
